/**
 * Avalara Shipping Verification for Beverage Alcohol
 * API for evaluating transactions against direct-to-consumer Beverage Alcohol shipping regulations.  This API is currently in beta. 
 *
 * The version of the OpenAPI document: 2.1.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class AgeVerifyFailureCode.
* @enum {}
* @readonly
*/
export default class AgeVerifyFailureCode {
    
        /**
         * value: "not_found"
         * @const
         */
        "not_found" = "not_found";

    
        /**
         * value: "dob_unverifiable"
         * @const
         */
        "dob_unverifiable" = "dob_unverifiable";

    
        /**
         * value: "under_age"
         * @const
         */
        "under_age" = "under_age";

    
        /**
         * value: "suspected_fraud"
         * @const
         */
        "suspected_fraud" = "suspected_fraud";

    
        /**
         * value: "deceased"
         * @const
         */
        "deceased" = "deceased";

    
        /**
         * value: "unknown_error"
         * @const
         */
        "unknown_error" = "unknown_error";

    

    /**
    * Returns a <code>AgeVerifyFailureCode</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/AgeVerifyFailureCode} The enum <code>AgeVerifyFailureCode</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

