/**
 * Avalara Shipping Verification for Beverage Alcohol
 * API for evaluating transactions against direct-to-consumer Beverage Alcohol shipping regulations.  This API is currently in beta. 
 *
 * The version of the OpenAPI document: 2.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ErrorDetailsError from './ErrorDetailsError';

/**
 * The ErrorDetails model module.
 * @module model/ErrorDetails
 * @version 2.1.4
 */
class ErrorDetails {
    /**
     * Constructs a new <code>ErrorDetails</code>.
     * Message Object
     * @alias module:model/ErrorDetails
     */
    constructor() { 
        
        ErrorDetails.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ErrorDetails</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ErrorDetails} obj Optional instance to populate.
     * @return {module:model/ErrorDetails} The populated <code>ErrorDetails</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ErrorDetails();

            if (data.hasOwnProperty('error')) {
                obj['error'] = ErrorDetailsError.constructFromObject(data['error']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ErrorDetailsError} error
 */
ErrorDetails.prototype['error'] = undefined;






export default ErrorDetails;

