/**
 * Avalara Shipping Verification for Beverage Alcohol
 * API for evaluating transactions against direct-to-consumer Beverage Alcohol shipping regulations.  This API is currently in beta. 
 *
 * The version of the OpenAPI document: 2.1.0-beta
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AvalaraNodeAsv);
  }
}(this, function(expect, AvalaraNodeAsv) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AvalaraNodeAsv.ErrorDetailsErrorDetails();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ErrorDetailsErrorDetails', function() {
    it('should create an instance of ErrorDetailsErrorDetails', function() {
      // uncomment below and update the code to test ErrorDetailsErrorDetails
      //var instance = new AvalaraNodeAsv.ErrorDetailsErrorDetails();
      //expect(instance).to.be.a(AvalaraNodeAsv.ErrorDetailsErrorDetails);
    });

    it('should have the property code (base name: "code")', function() {
      // uncomment below and update the code to test the property code
      //var instance = new AvalaraNodeAsv.ErrorDetailsErrorDetails();
      //expect(instance).to.be();
    });

    it('should have the property message (base name: "message")', function() {
      // uncomment below and update the code to test the property message
      //var instance = new AvalaraNodeAsv.ErrorDetailsErrorDetails();
      //expect(instance).to.be();
    });

    it('should have the property number (base name: "number")', function() {
      // uncomment below and update the code to test the property number
      //var instance = new AvalaraNodeAsv.ErrorDetailsErrorDetails();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new AvalaraNodeAsv.ErrorDetailsErrorDetails();
      //expect(instance).to.be();
    });

    it('should have the property faultCode (base name: "faultCode")', function() {
      // uncomment below and update the code to test the property faultCode
      //var instance = new AvalaraNodeAsv.ErrorDetailsErrorDetails();
      //expect(instance).to.be();
    });

    it('should have the property helpLink (base name: "helpLink")', function() {
      // uncomment below and update the code to test the property helpLink
      //var instance = new AvalaraNodeAsv.ErrorDetailsErrorDetails();
      //expect(instance).to.be();
    });

    it('should have the property severity (base name: "severity")', function() {
      // uncomment below and update the code to test the property severity
      //var instance = new AvalaraNodeAsv.ErrorDetailsErrorDetails();
      //expect(instance).to.be();
    });

  });

}));
