/**
 * Avalara Shipping Verification for Beverage Alcohol
 * API for evaluating transactions against direct-to-consumer Beverage Alcohol shipping regulations.  This API is currently in beta. 
 *
 * The version of the OpenAPI document: 2.1.0-beta
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AvalaraNodeAsv);
  }
}(this, function(expect, AvalaraNodeAsv) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AvalaraNodeAsv.ShippingVerifyResult();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ShippingVerifyResult', function() {
    it('should create an instance of ShippingVerifyResult', function() {
      // uncomment below and update the code to test ShippingVerifyResult
      //var instance = new AvalaraNodeAsv.ShippingVerifyResult();
      //expect(instance).to.be.a(AvalaraNodeAsv.ShippingVerifyResult);
    });

    it('should have the property compliant (base name: "compliant")', function() {
      // uncomment below and update the code to test the property compliant
      //var instance = new AvalaraNodeAsv.ShippingVerifyResult();
      //expect(instance).to.be();
    });

    it('should have the property message (base name: "message")', function() {
      // uncomment below and update the code to test the property message
      //var instance = new AvalaraNodeAsv.ShippingVerifyResult();
      //expect(instance).to.be();
    });

    it('should have the property successMessages (base name: "successMessages")', function() {
      // uncomment below and update the code to test the property successMessages
      //var instance = new AvalaraNodeAsv.ShippingVerifyResult();
      //expect(instance).to.be();
    });

    it('should have the property failureMessages (base name: "failureMessages")', function() {
      // uncomment below and update the code to test the property failureMessages
      //var instance = new AvalaraNodeAsv.ShippingVerifyResult();
      //expect(instance).to.be();
    });

    it('should have the property failureCodes (base name: "failureCodes")', function() {
      // uncomment below and update the code to test the property failureCodes
      //var instance = new AvalaraNodeAsv.ShippingVerifyResult();
      //expect(instance).to.be();
    });

    it('should have the property warningCodes (base name: "warningCodes")', function() {
      // uncomment below and update the code to test the property warningCodes
      //var instance = new AvalaraNodeAsv.ShippingVerifyResult();
      //expect(instance).to.be();
    });

    it('should have the property lines (base name: "lines")', function() {
      // uncomment below and update the code to test the property lines
      //var instance = new AvalaraNodeAsv.ShippingVerifyResult();
      //expect(instance).to.be();
    });

  });

}));
