/**
 * Avalara Shipping Verification for Beverage Alcohol
 * API for evaluating transactions against direct-to-consumer Beverage Alcohol shipping regulations.  This API is currently in beta. 
 *
 * The version of the OpenAPI document: 2.1.0-beta
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AvalaraNodeAsv);
  }
}(this, function(expect, AvalaraNodeAsv) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AvalaraNodeAsv.ShippingVerificationApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ShippingVerificationApi', function() {
    describe('deregisterShipment', function() {
      it('should call deregisterShipment successfully', function(done) {
        //uncomment below and update the code to test deregisterShipment
        //instance.deregisterShipment(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('registerShipment', function() {
      it('should call registerShipment successfully', function(done) {
        //uncomment below and update the code to test registerShipment
        //instance.registerShipment(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('registerShipmentIfCompliant', function() {
      it('should call registerShipmentIfCompliant successfully', function(done) {
        //uncomment below and update the code to test registerShipmentIfCompliant
        //instance.registerShipmentIfCompliant(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('verifyShipment', function() {
      it('should call verifyShipment successfully', function(done) {
        //uncomment below and update the code to test verifyShipment
        //instance.verifyShipment(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
