# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request_target:
    types:
      - opened
    branches:    
      - 'main'
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-package:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - run: cd dist
      - run: npm link
      - run: cd ..
      - run: npm link avalara-sdk
      - run: npm run test --username=${{ secrets.API_USERNAME }} --password=${{ secrets.API_PASSWORD }}
